### PR TITLE
Update UI colours

### PR DESCRIPTION
**Pull request by brendanng7**
Updates the colours of contact mate.

Will have to wait for #184 to be finished too before closing #170

### CODE REVIEW

**Comment by brendanng7** [comment]
image
image
image

**Comment by brendanng7** [comment]
image

**Comment by GabrielCWT** [comment]
> Need suggestions for what colour to use for the profile part

Maybe follow the lighter card colour (Even rows). Also the profile card only has 1 corner rounded

**Comment by GabrielCWT** [comment]
Could I also just check, you added a light theme but is it right to say that the dark theme is no longer in use?

**Comment by brendanng7** [comment]
Yep the dark theme is no longer in use, just thought it would be better to leave the original theme there.

The 1 corner rounded was on purpose lol

**Review by GabrielCWT — APPROVED** [review]
Merge when you are ready!

**Pull request merged**
